version: '3.6'

volumes:
  wordpress:
  dbdata:


networks:
  app-network:
    driver: bridge


services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: wordpress_adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - app-network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    env_file: .env
    depends_on:
      - db
    ports:
      - 8081:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ~/wordpress/data:/var/www/html/wp-content
    networks:
      - app-network
